<?php

$idConcept = $this->params()->fromPost('id', '');
$rapports = $this->params()->fromPost('rapports', '');
$idRt = $this->params()->fromPost('idRt', '');
$user = $this->identity();

//création des rapports
$ca = $this->CartoAffectFactory(['user'=>$user, 'idCpt'=>$idConcept, 'rapports'=>$rapports
  , 'idRt'=>$idRt
  //TODO:retrouver les themeSetting dans le module
  , 'themeSetting'=>['rt_idRapport'=>$this->themeSetting('rt_idRapport'),'rt_idSonar'=>$this->themeSetting('rt_idSonar')]
  ]);

//traitement suivant le ressource template
switch ($idRt) {
  case $this->themeSetting('rt_idRapport'):
    //récupère le réseau de concept
    $rt =  $this->api()->read('resource_templates', $idRt)->getContent();
    $result = $this->ReseauConcept($ca['concept'], $ca['actant'], $rt);
    break;
  case $this->themeSetting('rt_idSonar'):
    //récupère les positions pour le concepts
    $result = $this->PosiSonar($rapports['jdc:hasDoc'][0]['value'], $rapports['ma:hasRatingSystem'][0]['value']);
    break;
}

echo json_encode($result);


?>