<?php

/*TODO:redirige si pas d'utilisateur connecté
if(!$this->identity())
        $this->toUrl('guest/login');
*/

$translate = $this->plugin('translate');

//récupère les utiles de la page
$props = $this->pageProps();
$urls = $this->pageUrls($props);

$item = $this->getItem($props);

//récupère l'actant 
$ca = $this->CartoAffectFactory(['user'=>$this->identity(),'itemCpt'=>$item]);
$actant = $ca['actant'];

//récupère la définition des rapports
//et le réseau du concept
$rt =  $this->api()->read('resource_templates', ['label' => 'Rapports entre concepts'])->getContent();
$rc = $this->ReseauConcept($item, $actant, $rt);
$dataReseauConcept=$rc['dataReseauConcept'];
$cptRapports=$rc['cptRapports'];

$urlSendRapports = "ajout-rapports";

?>

<div class="alert alert-dark text-center" role="alert">
        <h4 class="alert-heading"><?php echo $item->link($item->displayTitle(),null,['class'=>'alert-link']); ?></h4>
        <?php if ($description = $item->displayDescription()): ?>
        <div class="description"><?php echo $description; ?></div>
        <?php endif; ?>
        <hr>
        <!-- la supression ce fait dans l'admin
        <a id='btnDelete' type="button" class="btn btn-danger btn-lg"
                href="<?php echo $item->adminUrl('delete');?>"
            data-toggle="tooltip" data-placement="bottom" title="supprimer le concept">
            <i class="fas fa-trash-alt"></i></a>
        -->
        <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Gestion des concepts">

                <div class="btn-group" role="group" aria-label="Outils d'édition des concepts">
                        <a id='btnEdit' href="<?php echo $item->adminUrl('edit');?>" type="button"
                                class="btn btn-dark btn-sm" data-toggle="tooltip" data-placement="bottom"
                                title="modifier le concept">
                                <i class="fas fa-edit"></i></a>
                        <button id='btnLink' type="button" class="btn btn-dark btn-sm" data-toggle="tooltip"
                                data-placement="bottom" title="relier le concept">
                                <i class="fas fa-link"></i></button>
                        <a id='btnEdit' href="explorer-concept?concept=<?php echo $item->displayTitle();?>" type="button"
                                class="btn btn-dark btn-sm" data-toggle="tooltip" data-placement="bottom"
                                title="explorer le concept">
                                <i class="fab fa-wpexplorer"></i></a>

                </div>

                <div class="input-group">
                        <div class="input-group-prepend">
                                <div class="input-group-text" id="btnFindConcept">
                                        <i id="icon-findTags" class="fas fa-search"></i>
                                        <div id="spin-findTags" style="display: none;"
                                                class="spinner-border spinner-border-sm"
                                                role="status">
                                                <span class="sr-only">Chargement...</span>
                                        </div>
                                </div>
                        </div>

                        <div class="ui-widget">
                                <input class="form-control" id="findTags" size="30" 
                                placeholder="saisir votre recherche"
                                aria-label="Trouver un concept" aria-describedby="btnFindConcept" >
                        </div>
                </div>
        </div>

</div>


<p id='contSvg'></p>

       

<div class="modal fade" id="modalAjoutSkos" tabindex="-1" role="dialog" aria-labelledby="modalAjoutSkos"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
                <div class="modal-content">
                        <div class="modal-header">
                                <h5 class="modal-title" id="ajoutConceptLabel"></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                        <div class="modal-body">

                                <div id="contAddCptRapports" class="container">
                                        <div class="row">
                                                <div class="col-sm">

                                                        <div class="ui-widget">
                                                                <label for="tags">Sélectionner un concept :</label>
                                                                <div id="spin-tags" style="display: none;"
                                                                        class="spinner-border spinner-border-sm"
                                                                        role="status">
                                                                        <span class="sr-only">Chargement...</span>
                                                                </div>
                                                                <input class="form-control" id="tags" size="64">
                                                        </div>
                                                </div>
                                        </div>
                                        <div class="row">
                                                <div class="col-sm">
                                                        <div class="dropdown-divider"></div>
                                                </div>
                                        </div>

                                </div>
                        </div>
                        <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                                <a href="#" class="btn btn-dark disabled" tabindex="-1" role="button" 
                                        id="modalBtnValiderRapports" aria-disabled="true">Valider</a>
                        </div>
                </div>
        </div>
</div>

<script>
        //construction du sankey
        let item = <?php echo json_encode($item); ?>;
        var rapports=<?php echo json_encode($cptRapports);?>;
        const urlAutoComplete = "<?php echo $urls['autoComplete'];?>", urlAutoCompleteRedir = "editer-concept?concept=",
                urlSendRapports = '<?php echo $urlSendRapports; ?>',
                rtRapport = "<?php echo $rt->id();?>";
        mHaut = d3.select('nav').node().clientHeight;

        es = new exploskos({
                'idCont': 'contSvg',
                'margin': {top: mHaut, right: 10, bottom: 10, left: 5},            
                'data': <?php echo json_encode($dataReseauConcept); ?>,
                'fctAjoutSkos':ajoutSkos,
                });
        d3.select("#btnLink").on("click",ajoutSkos);
        d3.select("#modalBtnValiderRapports").on("click",sendrapports);

    //initialisation de l'interface
    $(function () {
        setAutoComplete('tags');
        setAutoComplete('findTags');
    });



</script>

