<?php

$translate = $this->plugin('translate');
//TODO: récupérer le nom de la page
$flux = "explorer-document";

$item = $this->getItem('document');

//récupère les utiles de la page
$props = $this->pageProps();
$urls = $this->pageUrls($props,$item,'document');

//récupère la collection des cribles
$itemSetCrible = $this->themeSetting('item_set_id_crible');
$cribles = $this->Crible($itemSetCrible);

//récupère la liste des cartographies pour cette page
$param = array();
$cartos =  $this->api()->search('items'
        , ['resource_template_id' => $props['rtCartoSemantique']->id()
        ,'property'=>[['property'=>$props['schema:target']->id(),'type'=>'eq','text'=>$flux]]
        ],['sort_by'=>'jdc:ordreCrible']
        )->getContent();
//TODO:classer directement dans la requête et pas dans le javascript

//récupère l'actant 
$ca = $this->CartoAffectFactory(['user'=>$this->identity(),'itemCpt'=>$item]);
$actant = $ca['actant'];

//récupère le réseau du document
$reseau = $this->ReseauDocument($item,$actant);

//récupère l'historique des usages du document
$dataTimeline = $this->HistoDocument($item, $props);


?>
<?php echo $this->partial('cartoaffect/menu-haut', ['item'=>$item]);?>

<div id='tlGraph'></div>

<div class="cartoSem" id="cartoSonar"></div>

<div class="cartoSem" id='cartoExploskos'></div>

<div class="cartoSem" id='cartoReseau'></div>


<?php echo $this->partial('cartoaffect/modal-skos', []);?>

<?php echo $this->partial('cartoaffect/modal-wait', []);?>

       
<script>
        const urlAutoComplete = "<?php echo $urls['autoComplete'];?>", urlAutoCompleteRedir = "<?php echo $urls['autoCompleteRedir'];?>",
                urlSendRapports = '<?php echo $urls['urlSendRapports']; ?>',
                urlDataSonar = '<?php echo $urls['urlDataSonar']; ?>',
                actant = <?php echo json_encode($actant); ?>,
                rtRapport = "<?php echo $props['rtRapport']->id();?>",
                rtSonar = "<?php echo $props['rtSonar']->id();?>";
        flux = '<?php echo $flux; ?>';
        item = <?php echo json_encode($item);?>; 
        cribles = <?php echo json_encode($cribles);?>; 
        cartos = <?php echo json_encode($cartos);?>;
        dtReseau = <?php echo json_encode($reseau);?>;
        dataTimeline = <?php echo json_encode($dataTimeline); ?>;

        window.onload = function() { 

                //initialisation de l'IHM
                initIHM();

                //initialisation des autocomplétion
                setAutoComplete('tags');
                setAutoComplete('findDocs');

                //initialisation de la timeline
                timelineInit();
        };

</script>

