<?php

$translate = $this->plugin('translate');

$flux = "explorer-concept";
$item = $this->getItem('concept');

//récupère les utiles de la page
$props = $this->pageProps();
$urls = $this->pageUrls($props, $item, 'concept');

//récupère la collection des cribles
$itemSetCrible = $this->themeSetting('item_set_id_crible');
$cribles = $this->Crible($itemSetCrible);
//récupère l'historique des usages du concept
$dataTimeline = $this->HistoConcept($item->id());

//récupère la liste des cartographies
$cartos =  $this->api()->search('items'
        , ['resource_template_id' => $props['rtCartoSemantique']->id()
        ,'property'=>[['property'=>$props['schema:target']->id(),'type'=>'eq','text'=>$flux]]
        ],['sort_by'=>'jdc:ordreCrible']
        )->getContent();

//récupère l'actant 
$ca = $this->CartoAffectFactory(['user'=>$this->identity(),'itemCpt'=>$item]);
$actant = $ca['actant'];

//TODO:mettre un sélecteur de ressource template dans les settings du thème
//récupère la définition des rapports
//et le réseau du concept
$rc = $this->ReseauConcept($item, $actant, $props['rtRapport']);
$dataReseauConcept=$rc['dataReseauConcept'];
$cptRapports=$rc['cptRapports'];

?>


<?php echo $this->partial('cartoaffect/menu-haut', ['item'=>$item]);?>

<div id='tlGraph'></div>

<div class="cartoSem" id="cartoSonar"></div>

<div class="cartoSem" id='cartoExploskos'></div>

<div class="cartoSem" id='cartoReseau'></div>


<?php echo $this->partial('cartoaffect/modal-skos', []);?>

<?php echo $this->partial('cartoaffect/modal-wait', []);?>



       
<script>

        const urlAutoComplete = "<?php echo $urls['autoComplete'];?>", 
                urlAutoCompleteRedir = "<?php echo $urls['autoCompleteRedir'];?>",
                urlSendRapports = '<?php echo $urls['urlSendRapports']; ?>',
                urlDataSonar = '<?php echo $urls['urlDataSonar']; ?>',
                actant = <?php echo json_encode($actant); ?>,
                rtRapport = "<?php echo $props['rtRapport']->id();?>",
                rtSonar = "<?php echo $props['rtSonar']->id();?>";
        flux = '<?php echo $flux; ?>';
        item = <?php echo json_encode($item);?>; 
        cribles = <?php echo json_encode($cribles);?>; 
        cartos = <?php echo json_encode($cartos);?>;
        rapports=<?php echo json_encode($cptRapports);?>,
        dataTimeline = <?php echo json_encode($dataTimeline); ?>,
        dataReseauConcept = <?php echo json_encode($dataReseauConcept); ?>;

        window.onload = function() { 

                //initialisation de l'IHM
                initIHM();

                //initialisation des autocomplétion
                setAutoComplete('tags');
                setAutoComplete('findDocs');

                //initialisation de la timeline
                timelineInit();
        };


</script>
