<?php
$item = $this->vars('item');
?>

<div class="alert alert-dark text-center" role="alert">
        <h4 class="alert-heading"><?php echo $item->link($item->displayTitle(),null,['class'=>'alert-link']); ?></h4>
        <?php if ($description = $item->displayDescription()): ?>
        <div class="description"><?php echo $description; ?></div>
        <?php endif; ?>
        <hr>
        
    <div class="btn-toolbar justify-content-between" role="toolbar" aria-label="Gestion des concepts">

                <div class="btn-group" role="group" aria-label="Outils d'édition des concepts">

                        <a id='btnShowHideTimeline' href="#" type="button"
                                class="btn btn-dark btn-sm" data-toggle="tooltip" data-placement="bottom"
                                title="Afficher l'historique des usages">
                                <i class="fas fa-history"></i></a>
                        <a id='btnEdit' href="<?php echo $item->adminUrl('edit');?>" type="button"
                                class="btn btn-dark btn-sm" data-toggle="tooltip" data-placement="bottom"
                                title="modifier le document">
                                <i class="fas fa-edit"></i></a>
                        <button id='btnLink' type="button" class="btn btn-dark btn-sm" data-toggle="tooltip"
                                data-placement="bottom" title="relier le concept">
                                <i class="fas fa-link"></i></button>

                </div>
                <div class="btn-group" role="group" aria-label="Outils d'évaluation des concepts">
                        <div class="btn-group">
                                <button id='btnCribles' class="btn btn-dark btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                cribles
                                </button>
                                <div id='ddCribles' class="dropdown-menu" aria-labelledby="btnCribles">
                                </div>
                        </div>
                        <button id='btnChoixCrible' class="btn btn-light btn-sm" type="button" >
                                ...
                        </button>
                        <div class="btn-group">
                                <button id='btnCartos' class="btn btn-dark btn-sm dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                cartographies
                                </button>
                                <div id='ddCartos' class="dropdown-menu" aria-labelledby="btnCartos">
                                </div>
                        </div>
                        <button id='btnChoixCarto' class="btn btn-light btn-sm" type="button" >
                                ...
                        </button>
                </div>

                <div class="input-group">
                        <div class="input-group-prepend">
                                <div class="input-group-text" id="btnFindConcept">
                                        <i id="icon-findDocs" class="fas fa-search"></i>
                                        <div id="spin-findDocs" style="display: none;"
                                                class="spinner-border spinner-border-sm"
                                                role="status">
                                                <span class="sr-only">Chargement...</span>
                                        </div>
                                </div>
                        </div>

                        <div class="ui-widget">
                                <input class="form-control" id="findDocs" size="30" 
                                placeholder="saisir votre recherche"
                                aria-label="Trouver un document" aria-describedby="btnFindDocument" >
                        </div>
                </div>
        </div>
    </div>
